version: '3'

volumes:
  keycloak_postgres_data:
  openfga_postgres_data:

services:
  keycloak:
    extends:
      # file: kafka-integration/docker-compose-kafka.yml
      file: docker-compose-keycloak.yml
      service: keycloak

  keycloak-postgres:
    extends:
      # file: kafka-integration/docker-compose-kafka.yml
      file: docker-compose-keycloak.yml
      service: keycloak-postgres
  
  openfga:
    extends:
      file: docker-compose-openfga.yml
      service: openfga

  openfga-postgres:
    extends:
      file: docker-compose-openfga.yml
      service: openfga-postgres

  openfga-migrate:
    extends:
      file: docker-compose-openfga.yml
      service: openfga-migrate

  store:
    extends:
      file: docker-compose-apps.yml
      service: store

  store-api:
    extends:
      file: docker-compose-apps.yml
      service: store-api

  # zookeeper:
  #   extends:
  #     file: kafka-integration/docker-compose-kafka.yml
  #     service: zookeeper
      
  # kafka:
  #   extends:
  #     file: kafka-integration/docker-compose-kafka.yml
  #     service: kafka

  # kafka-consumer-openfga:
  #   extends:
  #     file: kafka-integration/docker-compose-kafka.yml
  #     service: kafka-consumer-openfga
