version: '3.8'

services:
  store:
    build: ./store-oidc-app
    image: twogenidentity/store-oidc-app
    container_name: store-oidc-app
    ports:
      - "9090:8080"
    environment: 
      VUE_APP_OIDC_PROVIDER_DOMAIN: http://localhost:8081/realms/master
      VUE_APP_API_URL: http://localhost:9091/api/products
      VUE_APP_CLIENT_ID: portal
    depends_on:
      keycloak:
        condition: service_healthy
          
  store-api:
    build: ./store-openfga-api
    image: twogenidentity/store-openfga-api
    container_name: store-openfga-api
    depends_on:
      keycloak:
        condition: service_healthy  
    ports:
      - "9091:9091"
    environment: 
      OIDC_PROVIDER_DOMAIN: http://localhost:8081/realms/master
