version: '3.8'

volumes:
  openfga_postgres_data:

services:
  openfga-postgres:
    image: postgres:14
    container_name: openfga-postgres
    volumes:
      - openfga_postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga-migrate:
    depends_on:
      openfga-postgres:
        condition: service_healthy
    image: openfga/openfga:v1.3.1
    container_name: openfga-migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@openfga-postgres:5432/postgres?sslmode=disable
    command: migrate
    networks:
      - default
  
  openfga:
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:v1.3.1
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@openfga-postgres:5432/postgres?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100
    networks:
      - default
    ports:
      - "8080:8080" #http
      - "3000:3000" #playground
